# Site settings
title: Startup Sales Bootcamp | The Free 5-Day Sales Buy-in Framework Course for Startups
email: julianacrispo@gmail.com
description: "In this free 5-day course, I’ll send you a daily email and video to take you through the Buy-in sales Framework."
url: "http://startupsalesbootcamp.com"
twitter_username: julianacrispo

github_username:  conradwa

# Build settings
markdown: kramdown
permalink: pretty
baseurl: ""
include: ["_fonts", "_bg_videos"]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  sass_dir: _sass